import type {
  SignalCatalogEntry,
  SignalKey,
} from '@/lib/signals/readiness-types';

type RawSignalCatalogEntry = Omit<SignalCatalogEntry, 'baseImpactScore'>;

const BASE_IMPACT_BY_STRENGTH = {
  weak: 24,
  medium: 52,
  strong: 78,
} as const;

const SIGNAL_IMPACT_OVERRIDES: Partial<Record<SignalKey, number>> = {
  funding_round: 74,
  grant_award: 48,
  ipo_or_follow_on: 84,
  milestone_payment: 72,
  partnership_with_upfront_economics: 76,
  ma_event: 44,
  demo_requested: 88,
  inbound_enquiry: 82,
  open_opportunity_in_crm: 72,
  new_contact_added_in_crm: 34,
  closed_lost_in_crm: 46,
  clinical_trial_registered: 46,
  clinical_trial_recruiting: 62,
  clinical_trial_completed: 34,
  clinical_trial_sponsor_change: 58,
  phase_transition: 82,
  trial_site_expansion: 68,
  indication_expansion: 56,
  breakthrough_designation: 49,
  fast_track_designation: 51,
  priority_review: 63,
  orphan_designation: 47,
  complete_response_letter: 64,
  fda_approval: 86,
  new_facility: 78,
  facility_expansion: 72,
  cmc_scale_up: 74,
  cdmo_partnership: 58,
  quality_compliance_buildout: 51,
  visited_your_website: 28,
  attended_your_webinar_or_event: 34,
  downloaded_your_content: 26,
  responded_to_previous_outreach: 62,
  cmc_hiring: 44,
  clinical_ops_hiring: 46,
  regulatory_hiring: 43,
  bd_hiring: 41,
  commercial_hiring: 39,
  job_surge: 36,
  new_to_role: 47,
  recently_promoted: 53,
  recently_changed_company: 57,
  new_internal_role: 49,
  title_change: 32,
  board_or_advisory_role: 31,
  partnership_deal: 63,
  licensing_deal: 67,
  co_development_deal: 66,
  regional_expansion: 58,
  commercialization_move: 64,
  platform_repositioning: 52,
  conference_presentation: 29,
  conference_speaker: 34,
  publication: 27,
  new_paper_published: 25,
  patent_filed_or_granted: 33,
  patent_application_published: 41,
  patent_granted: 52,
  new_therapeutic_area_patent: 57,
  assignee_portfolio_acceleration: 46,
  layoffs: 58,
  trial_failure_or_halt: 92,
  program_discontinuation: 88,
  restructuring: 63,
  distressed_financing: 95,
  acquisition_distraction: 54,
  leadership_churn: 57,
  lapsed_customer: 52,
  prior_customer_relationship: 76,
  prior_active_deal_relationship: 58,
  prior_pipeline_relationship: 30,
  key_contact_departed: 52,
};

function withImpact(entry: RawSignalCatalogEntry): SignalCatalogEntry {
  return {
    ...entry,
    baseImpactScore:
      SIGNAL_IMPACT_OVERRIDES[entry.signalKey] ??
      BASE_IMPACT_BY_STRENGTH[entry.defaultStrength],
  };
}

const RAW_READINESS_SIGNAL_CATALOG: readonly RawSignalCatalogEntry[] = [
  {
    signalKey: 'funding_round',
    scope: 'company',
    dimensions: ['new_budget'],
    defaultStrength: 'strong',
    defaultConfidence: 'high',
    decayDays: 270,
    buyerFunctions: ['executive_leadership', 'strategy_and_corporate_development', 'procurement'],
    intentMechanisms: ['budget_created'],
    notes: 'Covers seed through later-stage private funding.',
  },
  {
    signalKey: 'grant_award',
    scope: 'company',
    dimensions: ['new_budget'],
    defaultStrength: 'medium',
    defaultConfidence: 'high',
    decayDays: 240,
    buyerFunctions: ['research_and_development', 'clinical_operations', 'procurement'],
    intentMechanisms: ['budget_created'],
    notes: 'Useful for non-dilutive life sciences funding.',
  },
  {
    signalKey: 'ipo_or_follow_on',
    scope: 'company',
    dimensions: ['new_budget'],
    defaultStrength: 'strong',
    defaultConfidence: 'high',
    decayDays: 365,
    buyerFunctions: ['executive_leadership', 'strategy_and_corporate_development'],
    intentMechanisms: ['budget_created'],
    notes: 'More relevant for public companies than early-stage private biotech.',
  },
  {
    signalKey: 'milestone_payment',
    scope: 'company',
    dimensions: ['new_budget'],
    defaultStrength: 'strong',
    defaultConfidence: 'medium',
    decayDays: 180,
    buyerFunctions: ['executive_leadership', 'business_development', 'procurement'],
    intentMechanisms: ['budget_created'],
    notes: 'Usually comes from partnership milestones.',
  },
  {
    signalKey: 'partnership_with_upfront_economics',
    scope: 'company',
    dimensions: ['new_budget', 'new_strategy'],
    defaultStrength: 'strong',
    defaultConfidence: 'medium',
    decayDays: 240,
    buyerFunctions: ['business_development', 'partnerships', 'strategy_and_corporate_development'],
    intentMechanisms: ['budget_created', 'strategy_shift'],
    notes: 'Upfront dollars plus changed operating scope.',
  },
  {
    signalKey: 'ma_event',
    scope: 'company',
    dimensions: ['new_budget', 'new_strategy', 'caution'],
    defaultStrength: 'medium',
    defaultConfidence: 'medium',
    decayDays: 300,
    buyerFunctions: ['executive_leadership', 'strategy_and_corporate_development'],
    intentMechanisms: ['budget_created', 'strategy_shift', 'suppression'],
    notes: 'Treat as ambiguous without follow-up context.',
  },
  {
    signalKey: 'demo_requested',
    scope: 'company',
    dimensions: ['new_budget', 'new_needs'],
    defaultStrength: 'strong',
    defaultConfidence: 'high',
    decayDays: 45,
    buyerFunctions: ['procurement', 'technology_and_systems', 'commercial'],
    intentMechanisms: ['commercial_interest', 'budget_created'],
    notes: 'First-party. Highest explicit intent.',
  },
  {
    signalKey: 'inbound_enquiry',
    scope: 'company',
    dimensions: ['new_budget', 'new_needs'],
    defaultStrength: 'strong',
    defaultConfidence: 'high',
    decayDays: 45,
    buyerFunctions: ['commercial', 'business_development'],
    intentMechanisms: ['commercial_interest', 'budget_created'],
    notes: 'First-party.',
  },
  {
    signalKey: 'open_opportunity_in_crm',
    scope: 'company',
    dimensions: ['new_budget'],
    defaultStrength: 'strong',
    defaultConfidence: 'high',
    decayDays: 60,
    buyerFunctions: ['commercial', 'sales_operations'],
    intentMechanisms: ['commercial_interest', 'budget_created'],
    notes: 'First-party CRM state, not public signal.',
  },
  {
    signalKey: 'new_contact_added_in_crm',
    scope: 'company',
    dimensions: ['new_people'],
    defaultStrength: 'medium',
    defaultConfidence: 'high',
    decayDays: 75,
    buyerFunctions: [],
    intentMechanisms: ['team_buildout', 'leadership_change'],
    notes: 'HubSpot CRM shows a new stakeholder or relevant contact added to an account.',
  },
  {
    signalKey: 'closed_lost_in_crm',
    scope: 'company',
    dimensions: ['caution'],
    defaultStrength: 'strong',
    defaultConfidence: 'high',
    decayDays: 120,
    buyerFunctions: ['commercial', 'sales_operations'],
    intentMechanisms: ['suppression'],
    notes: 'First-party CRM caution state. Keeps closed-lost accounts dormant until something materially changes.',
  },
  {
    signalKey: 'clinical_trial_registered',
    scope: 'company',
    dimensions: ['new_needs'],
    defaultStrength: 'medium',
    defaultConfidence: 'high',
    decayDays: 180,
    buyerFunctions: ['clinical_operations', 'regulatory_affairs'],
    intentMechanisms: ['program_advance', 'complexity_increased'],
    notes: 'Stronger when paired with hiring or site expansion.',
  },
  {
    signalKey: 'clinical_trial_recruiting',
    scope: 'company',
    dimensions: ['new_needs'],
    defaultStrength: 'strong',
    defaultConfidence: 'high',
    decayDays: 150,
    buyerFunctions: ['clinical_operations', 'regulatory_affairs', 'data_and_informatics'],
    intentMechanisms: ['complexity_increased', 'program_advance'],
    notes: 'Active recruitment usually implies immediate operational demand.',
  },
  {
    signalKey: 'clinical_trial_completed',
    scope: 'company',
    dimensions: ['new_strategy'],
    defaultStrength: 'weak',
    defaultConfidence: 'high',
    decayDays: 120,
    buyerFunctions: ['clinical_operations', 'medical_affairs'],
    intentMechanisms: ['strategy_shift'],
    notes: 'Useful context signal, typically weaker for net-new buying intent.',
  },
  {
    signalKey: 'clinical_trial_sponsor_change',
    scope: 'company',
    dimensions: ['new_needs', 'new_strategy'],
    defaultStrength: 'medium',
    defaultConfidence: 'medium',
    decayDays: 180,
    buyerFunctions: ['clinical_operations', 'business_development', 'procurement'],
    intentMechanisms: ['strategy_shift', 'complexity_increased'],
    notes: 'Sponsor ownership changes can indicate a fresh buying center and new vendor decisions.',
  },
  {
    signalKey: 'phase_transition',
    scope: 'company',
    dimensions: ['new_needs', 'new_strategy'],
    defaultStrength: 'strong',
    defaultConfidence: 'high',
    decayDays: 210,
    buyerFunctions: ['clinical_operations', 'regulatory_affairs', 'manufacturing_and_cmc'],
    intentMechanisms: ['program_advance', 'complexity_increased'],
    notes: 'One of the highest-value biotech signals.',
  },
  {
    signalKey: 'trial_site_expansion',
    scope: 'company',
    dimensions: ['new_needs'],
    defaultStrength: 'strong',
    defaultConfidence: 'medium',
    decayDays: 150,
    buyerFunctions: ['clinical_operations', 'data_and_informatics'],
    intentMechanisms: ['complexity_increased'],
    notes: 'Operationally meaningful.',
  },
  {
    signalKey: 'indication_expansion',
    scope: 'company',
    dimensions: ['new_needs', 'new_strategy'],
    defaultStrength: 'medium',
    defaultConfidence: 'high',
    decayDays: 210,
    buyerFunctions: ['clinical_operations', 'regulatory_affairs', 'commercial'],
    intentMechanisms: ['program_advance', 'strategy_shift'],
    notes: 'Dual-maps by design.',
  },
  {
    signalKey: 'breakthrough_designation',
    scope: 'company',
    dimensions: ['new_needs'],
    defaultStrength: 'medium',
    defaultConfidence: 'high',
    decayDays: 180,
    buyerFunctions: ['regulatory_affairs', 'clinical_operations'],
    intentMechanisms: ['program_advance'],
    notes: 'Strong contextual support.',
  },
  {
    signalKey: 'fast_track_designation',
    scope: 'company',
    dimensions: ['new_needs'],
    defaultStrength: 'medium',
    defaultConfidence: 'high',
    decayDays: 180,
    buyerFunctions: ['regulatory_affairs', 'clinical_operations'],
    intentMechanisms: ['program_advance'],
    notes: 'Regulatory acceleration signal for near-term program execution.',
  },
  {
    signalKey: 'priority_review',
    scope: 'company',
    dimensions: ['new_needs', 'new_strategy'],
    defaultStrength: 'strong',
    defaultConfidence: 'high',
    decayDays: 180,
    buyerFunctions: ['regulatory_affairs', 'clinical_operations', 'commercial'],
    intentMechanisms: ['program_advance', 'strategy_shift'],
    notes: 'Compressed review timeline can pull forward launch and operational demand.',
  },
  {
    signalKey: 'orphan_designation',
    scope: 'company',
    dimensions: ['new_strategy'],
    defaultStrength: 'medium',
    defaultConfidence: 'high',
    decayDays: 240,
    buyerFunctions: ['regulatory_affairs', 'strategy_and_corporate_development'],
    intentMechanisms: ['strategy_shift', 'program_advance'],
    notes: 'Signals focused strategic positioning around rare-disease programs.',
  },
  {
    signalKey: 'complete_response_letter',
    scope: 'company',
    dimensions: ['caution'],
    defaultStrength: 'strong',
    defaultConfidence: 'high',
    decayDays: 180,
    buyerFunctions: ['regulatory_affairs', 'quality_and_compliance', 'executive_leadership'],
    intentMechanisms: ['suppression'],
    notes: 'Regulatory setback signal that should reduce near-term readiness.',
  },
  {
    signalKey: 'fda_approval',
    scope: 'company',
    dimensions: ['new_needs', 'new_strategy'],
    defaultStrength: 'strong',
    defaultConfidence: 'high',
    decayDays: 300,
    buyerFunctions: ['commercial', 'regulatory_affairs', 'quality_and_compliance'],
    intentMechanisms: ['program_advance', 'strategy_shift'],
    notes: 'Can imply commercialization readiness.',
  },
  {
    signalKey: 'new_facility',
    scope: 'company',
    dimensions: ['new_needs'],
    defaultStrength: 'strong',
    defaultConfidence: 'medium',
    decayDays: 240,
    buyerFunctions: ['manufacturing_and_cmc', 'quality_and_compliance', 'lab_operations'],
    intentMechanisms: ['complexity_increased'],
    notes: 'Very strong for CDMO/CMC-adjacent selling motions.',
  },
  {
    signalKey: 'facility_expansion',
    scope: 'company',
    dimensions: ['new_needs'],
    defaultStrength: 'strong',
    defaultConfidence: 'medium',
    decayDays: 240,
    buyerFunctions: ['manufacturing_and_cmc', 'quality_and_compliance'],
    intentMechanisms: ['complexity_increased'],
    notes: 'Similar to new_facility but expansion-specific.',
  },
  {
    signalKey: 'cmc_scale_up',
    scope: 'company',
    dimensions: ['new_needs'],
    defaultStrength: 'strong',
    defaultConfidence: 'medium',
    decayDays: 180,
    buyerFunctions: ['manufacturing_and_cmc', 'quality_and_compliance', 'procurement'],
    intentMechanisms: ['complexity_increased'],
    notes: 'Can be inferred from multiple manufacturing events.',
  },
  {
    signalKey: 'cdmo_partnership',
    scope: 'company',
    dimensions: ['new_needs', 'new_strategy'],
    defaultStrength: 'medium',
    defaultConfidence: 'medium',
    decayDays: 180,
    buyerFunctions: ['manufacturing_and_cmc', 'business_development'],
    intentMechanisms: ['complexity_increased', 'strategy_shift'],
    notes: 'Depends on context and transaction size.',
  },
  {
    signalKey: 'quality_compliance_buildout',
    scope: 'company',
    dimensions: ['new_needs'],
    defaultStrength: 'medium',
    defaultConfidence: 'medium',
    decayDays: 150,
    buyerFunctions: ['quality_and_compliance', 'regulatory_affairs'],
    intentMechanisms: ['complexity_increased'],
    notes: 'Often inferred from role mix rather than a single event.',
  },
  {
    signalKey: 'visited_your_website',
    scope: 'company',
    dimensions: ['new_needs'],
    defaultStrength: 'medium',
    defaultConfidence: 'high',
    decayDays: 21,
    buyerFunctions: ['marketing', 'commercial'],
    intentMechanisms: ['commercial_interest'],
    notes: 'First-party; weaker than demo/inbound.',
  },
  {
    signalKey: 'attended_your_webinar_or_event',
    scope: 'company',
    dimensions: ['new_needs'],
    defaultStrength: 'medium',
    defaultConfidence: 'high',
    decayDays: 30,
    buyerFunctions: ['marketing', 'commercial'],
    intentMechanisms: ['commercial_interest'],
    notes: 'First-party; contextual unless repeated.',
  },
  {
    signalKey: 'downloaded_your_content',
    scope: 'company',
    dimensions: ['new_needs'],
    defaultStrength: 'medium',
    defaultConfidence: 'high',
    decayDays: 21,
    buyerFunctions: ['marketing', 'commercial'],
    intentMechanisms: ['commercial_interest'],
    notes: 'First-party.',
  },
  {
    signalKey: 'responded_to_previous_outreach',
    scope: 'contact',
    dimensions: ['new_needs'],
    defaultStrength: 'strong',
    defaultConfidence: 'high',
    decayDays: 30,
    buyerFunctions: [],
    intentMechanisms: ['commercial_interest'],
    notes: 'Buyer function should be derived from the contact classification.',
  },
  {
    signalKey: 'cmc_hiring',
    scope: 'company',
    dimensions: ['new_people', 'new_needs'],
    defaultStrength: 'strong',
    defaultConfidence: 'medium',
    decayDays: 120,
    buyerFunctions: ['manufacturing_and_cmc', 'quality_and_compliance'],
    intentMechanisms: ['team_buildout', 'complexity_increased'],
    notes: 'High-value life-sciences-specific signal.',
  },
  {
    signalKey: 'clinical_ops_hiring',
    scope: 'company',
    dimensions: ['new_people', 'new_needs'],
    defaultStrength: 'strong',
    defaultConfidence: 'medium',
    decayDays: 120,
    buyerFunctions: ['clinical_operations', 'data_and_informatics'],
    intentMechanisms: ['team_buildout', 'complexity_increased'],
    notes: 'Strong when tied to program growth.',
  },
  {
    signalKey: 'regulatory_hiring',
    scope: 'company',
    dimensions: ['new_people', 'new_needs'],
    defaultStrength: 'medium',
    defaultConfidence: 'medium',
    decayDays: 120,
    buyerFunctions: ['regulatory_affairs', 'quality_and_compliance'],
    intentMechanisms: ['team_buildout', 'complexity_increased'],
    notes: 'Often paired with milestone progression.',
  },
  {
    signalKey: 'bd_hiring',
    scope: 'company',
    dimensions: ['new_people', 'new_strategy'],
    defaultStrength: 'medium',
    defaultConfidence: 'medium',
    decayDays: 120,
    buyerFunctions: ['business_development', 'partnerships'],
    intentMechanisms: ['team_buildout', 'strategy_shift'],
    notes: 'Stronger for partnering/commercialization motions.',
  },
  {
    signalKey: 'commercial_hiring',
    scope: 'company',
    dimensions: ['new_people', 'new_strategy'],
    defaultStrength: 'medium',
    defaultConfidence: 'medium',
    decayDays: 120,
    buyerFunctions: ['commercial', 'marketing'],
    intentMechanisms: ['team_buildout', 'strategy_shift'],
    notes: 'Often a commercialization readiness clue.',
  },
  {
    signalKey: 'job_surge',
    scope: 'company',
    dimensions: ['new_people', 'new_needs'],
    defaultStrength: 'medium',
    defaultConfidence: 'medium',
    decayDays: 90,
    buyerFunctions: ['manufacturing_and_cmc', 'clinical_operations', 'regulatory_affairs', 'business_development', 'commercial'],
    intentMechanisms: ['team_buildout', 'complexity_increased'],
    notes: 'Should be computed from classified role mix, not ingested directly if possible.',
  },
  {
    signalKey: 'new_to_role',
    scope: 'contact',
    dimensions: ['new_people'],
    defaultStrength: 'medium',
    defaultConfidence: 'medium',
    decayDays: 90,
    buyerFunctions: [],
    intentMechanisms: ['leadership_change'],
    notes: 'Buyer function should be derived from the contact classification.',
  },
  {
    signalKey: 'recently_promoted',
    scope: 'contact',
    dimensions: ['new_people'],
    defaultStrength: 'medium',
    defaultConfidence: 'medium',
    decayDays: 90,
    buyerFunctions: [],
    intentMechanisms: ['leadership_change'],
    notes: 'Buyer function should be derived from the contact classification.',
  },
  {
    signalKey: 'recently_changed_company',
    scope: 'contact',
    dimensions: ['new_people'],
    defaultStrength: 'medium',
    defaultConfidence: 'medium',
    decayDays: 120,
    buyerFunctions: [],
    intentMechanisms: ['leadership_change'],
    notes: 'Buyer function should be derived from the contact classification.',
  },
  {
    signalKey: 'new_internal_role',
    scope: 'contact',
    dimensions: ['new_people'],
    defaultStrength: 'medium',
    defaultConfidence: 'medium',
    decayDays: 90,
    buyerFunctions: [],
    intentMechanisms: ['leadership_change'],
    notes: 'Buyer function should be derived from the contact classification.',
  },
  {
    signalKey: 'title_change',
    scope: 'contact',
    dimensions: ['new_people'],
    defaultStrength: 'weak',
    defaultConfidence: 'medium',
    decayDays: 60,
    buyerFunctions: [],
    intentMechanisms: ['leadership_change'],
    notes: 'Buyer function should be derived from the contact classification.',
  },
  {
    signalKey: 'board_or_advisory_role',
    scope: 'contact',
    dimensions: ['new_people', 'new_strategy'],
    defaultStrength: 'weak',
    defaultConfidence: 'medium',
    decayDays: 180,
    buyerFunctions: [],
    intentMechanisms: ['leadership_change', 'strategy_shift'],
    notes: 'Buyer function should be derived from the contact classification.',
  },
  {
    signalKey: 'partnership_deal',
    scope: 'company',
    dimensions: ['new_strategy'],
    defaultStrength: 'medium',
    defaultConfidence: 'medium',
    decayDays: 180,
    buyerFunctions: ['business_development', 'partnerships'],
    intentMechanisms: ['strategy_shift'],
    notes: 'Use when economics are unknown.',
  },
  {
    signalKey: 'licensing_deal',
    scope: 'company',
    dimensions: ['new_strategy', 'new_budget'],
    defaultStrength: 'strong',
    defaultConfidence: 'medium',
    decayDays: 240,
    buyerFunctions: ['business_development', 'partnerships', 'strategy_and_corporate_development'],
    intentMechanisms: ['strategy_shift', 'budget_created'],
    notes: 'Map to budget if there is disclosed economics.',
  },
  {
    signalKey: 'co_development_deal',
    scope: 'company',
    dimensions: ['new_strategy', 'new_needs'],
    defaultStrength: 'medium',
    defaultConfidence: 'medium',
    decayDays: 180,
    buyerFunctions: ['business_development', 'clinical_operations'],
    intentMechanisms: ['strategy_shift', 'complexity_increased'],
    notes: 'Often operationally meaningful.',
  },
  {
    signalKey: 'regional_expansion',
    scope: 'company',
    dimensions: ['new_strategy'],
    defaultStrength: 'medium',
    defaultConfidence: 'medium',
    decayDays: 180,
    buyerFunctions: ['commercial', 'regulatory_affairs'],
    intentMechanisms: ['strategy_shift'],
    notes: 'Includes geographic expansion.',
  },
  {
    signalKey: 'commercialization_move',
    scope: 'company',
    dimensions: ['new_strategy', 'new_needs'],
    defaultStrength: 'strong',
    defaultConfidence: 'medium',
    decayDays: 210,
    buyerFunctions: ['commercial', 'quality_and_compliance', 'regulatory_affairs'],
    intentMechanisms: ['strategy_shift', 'complexity_increased'],
    notes: 'Important late-stage / approved product signal.',
  },
  {
    signalKey: 'platform_repositioning',
    scope: 'company',
    dimensions: ['new_strategy'],
    defaultStrength: 'medium',
    defaultConfidence: 'low',
    decayDays: 150,
    buyerFunctions: ['executive_leadership', 'strategy_and_corporate_development'],
    intentMechanisms: ['strategy_shift'],
    notes: 'Usually inferred from language changes or repeated events.',
  },
  {
    signalKey: 'conference_presentation',
    scope: 'company',
    dimensions: ['new_strategy'],
    defaultStrength: 'weak',
    defaultConfidence: 'medium',
    decayDays: 30,
    buyerFunctions: ['medical_affairs', 'research_and_development'],
    intentMechanisms: ['strategy_shift'],
    notes: 'Mostly contextual support.',
  },
  {
    signalKey: 'conference_speaker',
    scope: 'contact',
    dimensions: ['new_strategy', 'new_people'],
    defaultStrength: 'weak',
    defaultConfidence: 'medium',
    decayDays: 30,
    buyerFunctions: [],
    intentMechanisms: ['strategy_shift', 'leadership_change'],
    notes: 'Buyer function should be derived from the contact classification.',
  },
  {
    signalKey: 'publication',
    scope: 'company',
    dimensions: ['new_strategy'],
    defaultStrength: 'weak',
    defaultConfidence: 'high',
    decayDays: 45,
    buyerFunctions: ['research_and_development', 'medical_affairs'],
    intentMechanisms: ['strategy_shift'],
    notes: 'Mostly narrative/context.',
  },
  {
    signalKey: 'new_paper_published',
    scope: 'contact',
    dimensions: ['new_strategy'],
    defaultStrength: 'weak',
    defaultConfidence: 'high',
    decayDays: 45,
    buyerFunctions: [],
    intentMechanisms: ['strategy_shift'],
    notes: 'Buyer function should be derived from the contact classification.',
  },
  {
    signalKey: 'patent_filed_or_granted',
    scope: 'company',
    dimensions: ['new_strategy'],
    defaultStrength: 'weak',
    defaultConfidence: 'high',
    decayDays: 120,
    buyerFunctions: ['research_and_development', 'strategy_and_corporate_development'],
    intentMechanisms: ['strategy_shift'],
    notes: 'Not enough alone to indicate buying timing.',
  },
  {
    signalKey: 'patent_application_published',
    scope: 'company',
    dimensions: ['new_strategy'],
    defaultStrength: 'medium',
    defaultConfidence: 'high',
    decayDays: 180,
    buyerFunctions: ['research_and_development', 'strategy_and_corporate_development'],
    intentMechanisms: ['strategy_shift', 'program_advance'],
    notes: 'New published applications can indicate active pipeline and IP investment.',
  },
  {
    signalKey: 'patent_granted',
    scope: 'company',
    dimensions: ['new_strategy', 'new_needs'],
    defaultStrength: 'medium',
    defaultConfidence: 'high',
    decayDays: 240,
    buyerFunctions: ['research_and_development', 'commercial', 'strategy_and_corporate_development'],
    intentMechanisms: ['strategy_shift', 'program_advance'],
    notes: 'Granted patents can support commercialization and program execution readiness.',
  },
  {
    signalKey: 'new_therapeutic_area_patent',
    scope: 'company',
    dimensions: ['new_strategy', 'new_needs'],
    defaultStrength: 'strong',
    defaultConfidence: 'medium',
    decayDays: 240,
    buyerFunctions: ['research_and_development', 'business_development', 'strategy_and_corporate_development'],
    intentMechanisms: ['strategy_shift', 'complexity_increased'],
    notes: 'Patent activity in a new therapeutic area implies expansion and net-new demand creation.',
  },
  {
    signalKey: 'assignee_portfolio_acceleration',
    scope: 'company',
    dimensions: ['new_strategy'],
    defaultStrength: 'medium',
    defaultConfidence: 'medium',
    decayDays: 150,
    buyerFunctions: ['research_and_development', 'strategy_and_corporate_development'],
    intentMechanisms: ['program_advance', 'strategy_shift'],
    notes: 'Higher filing/grant velocity often indicates rising program tempo.',
  },
  {
    signalKey: 'layoffs',
    scope: 'company',
    dimensions: ['caution'],
    defaultStrength: 'strong',
    defaultConfidence: 'medium',
    decayDays: 180,
    buyerFunctions: ['executive_leadership', 'procurement'],
    intentMechanisms: ['suppression'],
    notes: 'Strong suppressor.',
  },
  {
    signalKey: 'trial_failure_or_halt',
    scope: 'company',
    dimensions: ['caution'],
    defaultStrength: 'strong',
    defaultConfidence: 'high',
    decayDays: 240,
    buyerFunctions: ['clinical_operations', 'executive_leadership'],
    intentMechanisms: ['suppression'],
    notes: 'Particularly important in biotech.',
  },
  {
    signalKey: 'program_discontinuation',
    scope: 'company',
    dimensions: ['caution'],
    defaultStrength: 'strong',
    defaultConfidence: 'high',
    decayDays: 240,
    buyerFunctions: ['research_and_development', 'clinical_operations'],
    intentMechanisms: ['suppression'],
    notes: 'Suppresses relevance for associated programs.',
  },
  {
    signalKey: 'restructuring',
    scope: 'company',
    dimensions: ['caution'],
    defaultStrength: 'strong',
    defaultConfidence: 'medium',
    decayDays: 180,
    buyerFunctions: ['executive_leadership', 'procurement'],
    intentMechanisms: ['suppression'],
    notes: 'Can coexist with strategy signals; caution should still apply.',
  },
  {
    signalKey: 'distressed_financing',
    scope: 'company',
    dimensions: ['caution'],
    defaultStrength: 'strong',
    defaultConfidence: 'medium',
    decayDays: 210,
    buyerFunctions: ['executive_leadership', 'strategy_and_corporate_development'],
    intentMechanisms: ['suppression'],
    notes: 'Different from healthy budget creation.',
  },
  {
    signalKey: 'acquisition_distraction',
    scope: 'company',
    dimensions: ['caution'],
    defaultStrength: 'medium',
    defaultConfidence: 'medium',
    decayDays: 150,
    buyerFunctions: ['executive_leadership', 'strategy_and_corporate_development'],
    intentMechanisms: ['suppression'],
    notes: 'Used when integration timing likely slows buying.',
  },
  {
    signalKey: 'leadership_churn',
    scope: 'company',
    dimensions: ['caution', 'new_people'],
    defaultStrength: 'medium',
    defaultConfidence: 'medium',
    decayDays: 120,
    buyerFunctions: ['executive_leadership', 'business_development', 'clinical_operations', 'manufacturing_and_cmc'],
    intentMechanisms: ['suppression', 'leadership_change'],
    notes: 'Can create change, but often noisy.',
  },
  {
    signalKey: 'prior_customer_relationship',
    scope: 'contact',
    dimensions: ['new_budget', 'new_people'],
    defaultStrength: 'strong',
    defaultConfidence: 'high',
    decayDays: 365,
    buyerFunctions: [],
    intentMechanisms: ['budget_created', 'leadership_change'],
    notes: 'Contact moved from a closed-won account. Strong warm-start signal at the new company.',
  },
  {
    signalKey: 'prior_active_deal_relationship',
    scope: 'contact',
    dimensions: ['new_budget', 'new_people'],
    defaultStrength: 'medium',
    defaultConfidence: 'high',
    decayDays: 180,
    buyerFunctions: [],
    intentMechanisms: ['budget_created', 'leadership_change'],
    notes: 'Contact moved from a company with an active deal in the pipeline.',
  },
  {
    signalKey: 'prior_pipeline_relationship',
    scope: 'contact',
    dimensions: ['new_people'],
    defaultStrength: 'weak',
    defaultConfidence: 'medium',
    decayDays: 90,
    buyerFunctions: [],
    intentMechanisms: ['leadership_change'],
    notes: 'Contact previously in the pipeline at their prior company (closed-lost or context-only).',
  },
  {
    signalKey: 'lapsed_customer',
    scope: 'company',
    dimensions: ['caution'],
    defaultStrength: 'medium',
    defaultConfidence: 'high',
    decayDays: 365,
    buyerFunctions: ['commercial'],
    intentMechanisms: ['suppression'],
    notes: 'First-party relationship warning.',
  },
  {
    signalKey: 'key_contact_departed',
    scope: 'company',
    dimensions: ['new_people', 'new_strategy'],
    defaultStrength: 'medium',
    defaultConfidence: 'high',
    decayDays: 120,
    buyerFunctions: [],
    intentMechanisms: ['leadership_change', 'strategy_shift'],
    notes: 'A known contact at this account moved to a new company. Creates an opportunity to re-establish with their replacement.',
  },
] as const;

export const READINESS_SIGNAL_CATALOG: readonly SignalCatalogEntry[] =
  RAW_READINESS_SIGNAL_CATALOG.map(withImpact);

export const READINESS_SIGNAL_CATALOG_BY_KEY: Readonly<Record<SignalKey, SignalCatalogEntry>> =
  READINESS_SIGNAL_CATALOG.reduce((acc, entry) => {
    acc[entry.signalKey] = entry;
    return acc;
  }, {} as Record<SignalKey, SignalCatalogEntry>);

export function getReadinessSignal(signalKey: SignalKey): SignalCatalogEntry {
  return READINESS_SIGNAL_CATALOG_BY_KEY[signalKey];
}

export function getSignalBaseImpactScore(signalKey: SignalKey): number {
  return READINESS_SIGNAL_CATALOG_BY_KEY[signalKey]?.baseImpactScore ?? 0;
}

export function getSignalsForDimension(dimension: SignalCatalogEntry['dimensions'][number]): SignalCatalogEntry[] {
  return READINESS_SIGNAL_CATALOG.filter((entry) => entry.dimensions.includes(dimension));
}
