import type {
  SignalCatalogEntry,
  SignalKey,
} from '@/lib/signals/readiness-types';

type RawSignalCatalogEntry = Omit<SignalCatalogEntry, 'baseImpactScore'>;

// Base impact per signal type (0–100). Rubric (locked 2026-06-02):
//   High 70–90   = direct buying intent, or a major event creating immediate
//                  need/budget
//   Medium 45–65 = org/operational change implying need is forming
//   Low 25–40    = context/narrative — weak intent
// Caution signals carry high "strength" but act as suppressors (handled in the
// dimension model), not positive drivers.
const SIGNAL_IMPACT_OVERRIDES: Partial<Record<SignalKey, number>> = {
  // Engagement / first-party — they're interacting with us, highest intent.
  demo_requested: 90,
  inbound_enquiry: 85,
  responded_to_previous_outreach: 70,
  attended_your_webinar_or_event: 50,
  downloaded_your_content: 45,
  visited_your_website: 42,
  // CRM relationship.
  open_opportunity_in_crm: 80,
  prior_customer_relationship: 72,
  prior_active_deal_relationship: 58,
  lapsed_customer: 55,
  prior_pipeline_relationship: 35,
  new_contact_added_in_crm: 34,
  // Money / capacity — budget + expansion.
  ipo_or_follow_on: 84,
  funding_round: 78,
  new_facility: 78,
  milestone_payment: 70,
  facility_expansion: 70,
  grant_award: 50,
  // Conference / in-market timing — a meeting window + reachability, not buying
  // intent. exhibiting (company commercial motion) > presenting (named contact,
  // personal hook) > attending (self-declared LinkedIn post, weak but timely).
  exhibiting_at_conference: 54,
  presenting_at_conference: 50,
  attending_conference: 40,
  // Deals / partnerships.
  partnership_with_upfront_economics: 78,
  commercialization_move: 70,
  licensing_deal: 67,
  co_development_deal: 66,
  partnership_deal: 60,
  // Clinical / regulatory.
  fda_approval: 86,
  phase_transition: 82,
  principal_investigator_new_trial: 72,
  trial_site_expansion: 68,
  complete_response_letter: 64,
  priority_review: 63,
  clinical_trial_recruiting: 62,
  clinical_trial_sponsor_change: 58,
  indication_expansion: 56,
  fast_track_designation: 51,
  breakthrough_designation: 50,
  orphan_designation: 47,
  clinical_trial_registered: 46,
  clinical_trial_completed: 40,
  // Hiring — org building.
  executive_hiring: 55,
  hiring_expansion: 50,
  cmc_hiring: 50,
  clinical_ops_hiring: 48,
  bd_hiring: 45,
  commercial_hiring: 45,
  regulatory_hiring: 45,
  research_hiring: 44,
  medical_hiring: 43,
  quality_hiring: 43,
  data_informatics_hiring: 42,
  // Contact / job change.
  recently_changed_company: 57,
  recently_promoted: 53,
  new_to_role: 50,
  new_internal_role: 49,
  title_change: 32,
  // IP / narrative — context, weak intent.
  new_therapeutic_area_patent: 50,
  assignee_portfolio_acceleration: 46,
  patent_granted: 40,
  patent_application_published: 38,
  patent_filed_or_granted: 33,
  publication: 27,
  new_paper_published: 25,
  // Caution / negative — suppress readiness (see overallScoreFromDimensions).
  trial_failure_or_halt: 92,
  program_discontinuation: 88,
  restructuring: 63,
  leadership_churn: 57,
  terminated_deal: 54,
  acquisition_distraction: 54,
  key_contact_departed: 52,
  closed_lost_in_crm: 46,
  ma_event: 44,
};

function withImpact(entry: RawSignalCatalogEntry): SignalCatalogEntry {
  return {
    ...entry,
    baseImpactScore: SIGNAL_IMPACT_OVERRIDES[entry.signalKey] ?? 52,
  };
}

const RAW_READINESS_SIGNAL_CATALOG: readonly RawSignalCatalogEntry[] = [
  {
    signalKey: 'funding_round',
    scope: 'company',
    dimensions: ['new_budget'],
    decayDays: 270,
    buyerFunctions: ['executive_leadership', 'strategy_and_corporate_development', 'procurement'],
    intentMechanisms: ['budget_created'],
    notes: 'Covers seed through later-stage private funding.',
  },
  {
    signalKey: 'grant_award',
    scope: 'company',
    dimensions: ['new_budget'],
    decayDays: 240,
    buyerFunctions: ['research_and_development', 'clinical_operations', 'procurement'],
    intentMechanisms: ['budget_created'],
    notes: 'Useful for non-dilutive life sciences funding.',
  },
  {
    signalKey: 'exhibiting_at_conference',
    scope: 'company',
    dimensions: ['new_needs', 'new_strategy'],
    // Lifecycle is phase-based (upcoming/live/recent), with a hard expiry 21d
    // post-event enforced in the monitor (conference-phase.ts). decayDays is the
    // scoring backstop so an emitted signal fades over ~the same window.
    decayDays: 30,
    buyerFunctions: ['business_development', 'commercial', 'partnerships'],
    intentMechanisms: ['commercial_interest'],
    notes: 'Company exhibiting at a relevant industry conference — in-market activity; phase drives the outreach angle.',
  },
  {
    signalKey: 'presenting_at_conference',
    scope: 'contact',
    dimensions: ['new_needs', 'new_strategy'],
    // Phase-based lifecycle + hard 21d post-event expiry in the monitor; decayDays backstop.
    decayDays: 30,
    buyerFunctions: ['research_and_development', 'clinical_operations', 'medical_affairs', 'commercial'],
    intentMechanisms: ['commercial_interest', 'strategy_shift'],
    notes: 'A tracked contact is a named speaker/presenter at a relevant conference — warm, contact-level outreach trigger.',
  },
  {
    signalKey: 'attending_conference',
    scope: 'contact',
    dimensions: ['new_needs', 'new_strategy'],
    decayDays: 30,
    buyerFunctions: ['business_development', 'commercial', 'partnerships'],
    intentMechanisms: ['commercial_interest'],
    notes: 'A tracked contact self-declared conference attendance on LinkedIn (in-window hashtag) — contact-level intent.',
  },
  {
    signalKey: 'ipo_or_follow_on',
    scope: 'company',
    dimensions: ['new_budget'],
    decayDays: 365,
    buyerFunctions: ['executive_leadership', 'strategy_and_corporate_development'],
    intentMechanisms: ['budget_created'],
    notes: 'More relevant for public companies than early-stage private biotech.',
  },
  {
    signalKey: 'milestone_payment',
    scope: 'company',
    dimensions: ['new_budget'],
    decayDays: 180,
    buyerFunctions: ['executive_leadership', 'business_development', 'procurement'],
    intentMechanisms: ['budget_created'],
    notes: 'Usually comes from partnership milestones.',
  },
  {
    signalKey: 'partnership_with_upfront_economics',
    scope: 'company',
    dimensions: ['new_budget', 'new_strategy'],
    decayDays: 240,
    buyerFunctions: ['business_development', 'partnerships', 'strategy_and_corporate_development'],
    intentMechanisms: ['budget_created', 'strategy_shift'],
    notes: 'Upfront dollars plus changed operating scope.',
  },
  {
    signalKey: 'ma_event',
    scope: 'company',
    dimensions: ['new_budget', 'new_strategy', 'new_people', 'new_needs'],
    decayDays: 300,
    buyerFunctions: ['executive_leadership', 'strategy_and_corporate_development'],
    intentMechanisms: ['budget_created', 'strategy_shift', 'team_buildout', 'complexity_increased'],
    notes: 'M&A brings fresh capital, strategic change, leadership transitions, and integration work.',
  },
  {
    signalKey: 'demo_requested',
    scope: 'company',
    dimensions: ['new_budget', 'new_needs'],
    decayDays: 45,
    buyerFunctions: ['procurement', 'technology_and_systems', 'commercial'],
    intentMechanisms: ['commercial_interest', 'budget_created'],
    notes: 'First-party. Highest explicit intent.',
  },
  {
    signalKey: 'inbound_enquiry',
    scope: 'company',
    dimensions: ['new_budget', 'new_needs'],
    decayDays: 45,
    buyerFunctions: ['commercial', 'business_development'],
    intentMechanisms: ['commercial_interest', 'budget_created'],
    notes: 'First-party.',
  },
  {
    signalKey: 'open_opportunity_in_crm',
    scope: 'company',
    dimensions: ['new_budget'],
    decayDays: 60,
    buyerFunctions: ['commercial', 'sales_operations'],
    intentMechanisms: ['commercial_interest', 'budget_created'],
    notes: 'First-party CRM state, not public signal.',
  },
  {
    signalKey: 'new_contact_added_in_crm',
    scope: 'company',
    dimensions: ['new_people'],
    decayDays: 75,
    buyerFunctions: [],
    intentMechanisms: ['team_buildout', 'leadership_change'],
    notes: 'HubSpot CRM shows a new stakeholder or relevant contact added to an account.',
  },
  {
    signalKey: 'closed_lost_in_crm',
    scope: 'company',
    dimensions: ['caution'],
    decayDays: 120,
    buyerFunctions: ['commercial', 'sales_operations'],
    intentMechanisms: ['suppression'],
    notes: 'First-party CRM caution state. Keeps closed-lost accounts dormant until something materially changes.',
  },
  {
    signalKey: 'clinical_trial_registered',
    scope: 'company',
    dimensions: ['new_needs'],
    decayDays: 180,
    buyerFunctions: ['clinical_operations', 'regulatory_affairs'],
    intentMechanisms: ['program_advance', 'complexity_increased'],
    notes: 'Stronger when paired with hiring or site expansion.',
  },
  {
    signalKey: 'clinical_trial_recruiting',
    scope: 'company',
    dimensions: ['new_needs'],
    decayDays: 150,
    buyerFunctions: ['clinical_operations', 'regulatory_affairs', 'data_and_informatics'],
    intentMechanisms: ['complexity_increased', 'program_advance'],
    notes: 'Active recruitment usually implies immediate operational demand.',
  },
  {
    signalKey: 'clinical_trial_completed',
    scope: 'company',
    dimensions: ['new_strategy'],
    decayDays: 120,
    buyerFunctions: ['clinical_operations', 'medical_affairs'],
    intentMechanisms: ['strategy_shift'],
    notes: 'Useful context signal, typically weaker for net-new buying intent.',
  },
  {
    signalKey: 'clinical_trial_sponsor_change',
    scope: 'company',
    dimensions: ['new_needs', 'new_strategy'],
    decayDays: 180,
    buyerFunctions: ['clinical_operations', 'business_development', 'procurement'],
    intentMechanisms: ['strategy_shift', 'complexity_increased'],
    notes: 'Sponsor ownership changes can indicate a fresh buying center and new vendor decisions.',
  },
  {
    signalKey: 'phase_transition',
    scope: 'company',
    dimensions: ['new_needs', 'new_strategy'],
    decayDays: 210,
    buyerFunctions: ['clinical_operations', 'regulatory_affairs', 'manufacturing_and_cmc'],
    intentMechanisms: ['program_advance', 'complexity_increased'],
    notes: 'One of the highest-value biotech signals.',
  },
  {
    signalKey: 'trial_site_expansion',
    scope: 'company',
    dimensions: ['new_needs'],
    decayDays: 150,
    buyerFunctions: ['clinical_operations', 'data_and_informatics'],
    intentMechanisms: ['complexity_increased'],
    notes: 'Operationally meaningful.',
  },
  {
    signalKey: 'indication_expansion',
    scope: 'company',
    dimensions: ['new_needs', 'new_strategy'],
    decayDays: 210,
    buyerFunctions: ['clinical_operations', 'regulatory_affairs', 'commercial'],
    intentMechanisms: ['program_advance', 'strategy_shift'],
    notes: 'Dual-maps by design.',
  },
  {
    signalKey: 'breakthrough_designation',
    scope: 'company',
    dimensions: ['new_needs'],
    decayDays: 180,
    buyerFunctions: ['regulatory_affairs', 'clinical_operations'],
    intentMechanisms: ['program_advance'],
    notes: 'Strong contextual support.',
  },
  {
    signalKey: 'fast_track_designation',
    scope: 'company',
    dimensions: ['new_needs'],
    decayDays: 180,
    buyerFunctions: ['regulatory_affairs', 'clinical_operations'],
    intentMechanisms: ['program_advance'],
    notes: 'Regulatory acceleration signal for near-term program execution.',
  },
  {
    signalKey: 'priority_review',
    scope: 'company',
    dimensions: ['new_needs', 'new_strategy'],
    decayDays: 180,
    buyerFunctions: ['regulatory_affairs', 'clinical_operations', 'commercial'],
    intentMechanisms: ['program_advance', 'strategy_shift'],
    notes: 'Compressed review timeline can pull forward launch and operational demand.',
  },
  {
    signalKey: 'orphan_designation',
    scope: 'company',
    dimensions: ['new_strategy'],
    decayDays: 240,
    buyerFunctions: ['regulatory_affairs', 'strategy_and_corporate_development'],
    intentMechanisms: ['strategy_shift', 'program_advance'],
    notes: 'Signals focused strategic positioning around rare-disease programs.',
  },
  {
    signalKey: 'complete_response_letter',
    scope: 'company',
    dimensions: ['caution'],
    decayDays: 180,
    buyerFunctions: ['regulatory_affairs', 'quality_and_compliance', 'executive_leadership'],
    intentMechanisms: ['suppression'],
    notes: 'Regulatory setback signal that should reduce near-term readiness.',
  },
  {
    signalKey: 'fda_approval',
    scope: 'company',
    dimensions: ['new_needs', 'new_strategy'],
    decayDays: 300,
    buyerFunctions: ['commercial', 'regulatory_affairs', 'quality_and_compliance'],
    intentMechanisms: ['program_advance', 'strategy_shift'],
    notes: 'Can imply commercialization readiness.',
  },
  {
    signalKey: 'new_facility',
    scope: 'company',
    dimensions: ['new_needs'],
    decayDays: 240,
    buyerFunctions: ['manufacturing_and_cmc', 'quality_and_compliance', 'lab_operations'],
    intentMechanisms: ['complexity_increased'],
    notes: 'Very strong for CDMO/CMC-adjacent selling motions.',
  },
  {
    signalKey: 'facility_expansion',
    scope: 'company',
    dimensions: ['new_needs'],
    decayDays: 240,
    buyerFunctions: ['manufacturing_and_cmc', 'quality_and_compliance'],
    intentMechanisms: ['complexity_increased'],
    notes: 'Similar to new_facility but expansion-specific.',
  },
  {
    signalKey: 'visited_your_website',
    scope: 'company',
    dimensions: ['new_needs'],
    decayDays: 21,
    buyerFunctions: ['marketing', 'commercial'],
    intentMechanisms: ['commercial_interest'],
    notes: 'First-party; weaker than demo/inbound.',
  },
  {
    signalKey: 'attended_your_webinar_or_event',
    scope: 'company',
    dimensions: ['new_needs'],
    decayDays: 30,
    buyerFunctions: ['marketing', 'commercial'],
    intentMechanisms: ['commercial_interest'],
    notes: 'First-party; contextual unless repeated.',
  },
  {
    signalKey: 'downloaded_your_content',
    scope: 'company',
    dimensions: ['new_needs'],
    decayDays: 21,
    buyerFunctions: ['marketing', 'commercial'],
    intentMechanisms: ['commercial_interest'],
    notes: 'First-party.',
  },
  {
    signalKey: 'responded_to_previous_outreach',
    scope: 'contact',
    dimensions: ['new_needs'],
    decayDays: 30,
    buyerFunctions: [],
    intentMechanisms: ['commercial_interest'],
    notes: 'Buyer function should be derived from the contact classification.',
  },
  {
    signalKey: 'cmc_hiring',
    scope: 'company',
    dimensions: ['new_people', 'new_needs'],
    decayDays: 120,
    buyerFunctions: ['manufacturing_and_cmc', 'quality_and_compliance'],
    intentMechanisms: ['team_buildout', 'complexity_increased'],
    notes: 'High-value life-sciences-specific signal.',
  },
  {
    signalKey: 'clinical_ops_hiring',
    scope: 'company',
    dimensions: ['new_people', 'new_needs'],
    decayDays: 120,
    buyerFunctions: ['clinical_operations', 'data_and_informatics'],
    intentMechanisms: ['team_buildout', 'complexity_increased'],
    notes: 'Strong when tied to program growth.',
  },
  {
    signalKey: 'regulatory_hiring',
    scope: 'company',
    dimensions: ['new_people', 'new_needs'],
    decayDays: 120,
    buyerFunctions: ['regulatory_affairs', 'quality_and_compliance'],
    intentMechanisms: ['team_buildout', 'complexity_increased'],
    notes: 'Often paired with milestone progression.',
  },
  {
    signalKey: 'research_hiring',
    scope: 'company',
    dimensions: ['new_people', 'new_needs', 'new_strategy'],
    decayDays: 120,
    buyerFunctions: ['research_and_development', 'lab_operations'],
    intentMechanisms: ['team_buildout', 'complexity_increased', 'strategy_shift'],
    notes: 'New program or indication starting — signals early pipeline expansion.',
  },
  {
    signalKey: 'quality_hiring',
    scope: 'company',
    dimensions: ['new_people', 'new_needs'],
    decayDays: 120,
    buyerFunctions: ['quality_and_compliance', 'manufacturing_and_cmc'],
    intentMechanisms: ['team_buildout', 'complexity_increased'],
    notes: 'Manufacturing ramp or audit readiness — often paired with CMC hiring.',
  },
  {
    signalKey: 'medical_hiring',
    scope: 'company',
    dimensions: ['new_people', 'new_strategy', 'new_needs'],
    decayDays: 120,
    buyerFunctions: ['medical_affairs', 'clinical_operations'],
    intentMechanisms: ['team_buildout', 'strategy_shift'],
    notes: 'New clinical phase entry or pre-launch medical affairs buildout.',
  },
  {
    signalKey: 'bd_hiring',
    scope: 'company',
    dimensions: ['new_people', 'new_strategy'],
    decayDays: 120,
    buyerFunctions: ['business_development', 'partnerships'],
    intentMechanisms: ['team_buildout', 'strategy_shift'],
    notes: 'Stronger for partnering/commercialization motions.',
  },
  {
    signalKey: 'commercial_hiring',
    scope: 'company',
    dimensions: ['new_people', 'new_strategy'],
    decayDays: 120,
    buyerFunctions: ['commercial', 'marketing'],
    intentMechanisms: ['team_buildout', 'strategy_shift'],
    notes: 'Often a commercialization readiness clue.',
  },
  {
    signalKey: 'data_informatics_hiring',
    scope: 'company',
    dimensions: ['new_people', 'new_needs'],
    decayDays: 120,
    buyerFunctions: ['data_and_informatics', 'technology_and_systems'],
    intentMechanisms: ['team_buildout', 'complexity_increased'],
    notes: 'Data infrastructure or trial-scale buildout — relevant for informatics and software vendors.',
  },
  {
    signalKey: 'executive_hiring',
    scope: 'company',
    dimensions: ['new_people', 'new_strategy'],
    decayDays: 90,
    buyerFunctions: ['executive_leadership', 'strategy_and_corporate_development'],
    intentMechanisms: ['leadership_change', 'strategy_shift'],
    notes: 'New VP/SVP/C-suite = new mandate and active vendor re-evaluation window.',
  },
  {
    signalKey: 'hiring_expansion',
    scope: 'company',
    dimensions: ['new_people', 'new_needs'],
    decayDays: 90,
    buyerFunctions: ['manufacturing_and_cmc', 'clinical_operations', 'regulatory_affairs', 'business_development', 'commercial'],
    intentMechanisms: ['team_buildout', 'complexity_increased'],
    notes: 'Broad hiring velocity signal (≥10 postings). Buyer functions derived from classified role mix at emit time.',
  },
  {
    signalKey: 'new_to_role',
    scope: 'contact',
    dimensions: ['new_people'],
    decayDays: 90,
    buyerFunctions: [],
    intentMechanisms: ['leadership_change'],
    notes: 'Buyer function should be derived from the contact classification.',
  },
  {
    signalKey: 'recently_promoted',
    scope: 'contact',
    dimensions: ['new_people'],
    decayDays: 90,
    buyerFunctions: [],
    intentMechanisms: ['leadership_change'],
    notes: 'Buyer function should be derived from the contact classification.',
  },
  {
    signalKey: 'recently_changed_company',
    scope: 'contact',
    dimensions: ['new_people'],
    decayDays: 120,
    buyerFunctions: [],
    intentMechanisms: ['leadership_change'],
    notes: 'Buyer function should be derived from the contact classification.',
  },
  {
    signalKey: 'new_internal_role',
    scope: 'contact',
    dimensions: ['new_people'],
    decayDays: 90,
    buyerFunctions: [],
    intentMechanisms: ['leadership_change'],
    notes: 'Buyer function should be derived from the contact classification.',
  },
  {
    signalKey: 'title_change',
    scope: 'contact',
    dimensions: ['new_people'],
    decayDays: 60,
    buyerFunctions: [],
    intentMechanisms: ['leadership_change'],
    notes: 'Buyer function should be derived from the contact classification.',
  },
  {
    signalKey: 'partnership_deal',
    scope: 'company',
    dimensions: ['new_strategy'],
    decayDays: 180,
    buyerFunctions: ['business_development', 'partnerships'],
    intentMechanisms: ['strategy_shift'],
    notes: 'Use when economics are unknown.',
  },
  {
    signalKey: 'licensing_deal',
    scope: 'company',
    dimensions: ['new_strategy', 'new_budget'],
    decayDays: 240,
    buyerFunctions: ['business_development', 'partnerships', 'strategy_and_corporate_development'],
    intentMechanisms: ['strategy_shift', 'budget_created'],
    notes: 'Map to budget if there is disclosed economics.',
  },
  {
    signalKey: 'co_development_deal',
    scope: 'company',
    dimensions: ['new_strategy', 'new_needs'],
    decayDays: 180,
    buyerFunctions: ['business_development', 'clinical_operations'],
    intentMechanisms: ['strategy_shift', 'complexity_increased'],
    notes: 'Often operationally meaningful.',
  },
  {
    signalKey: 'commercialization_move',
    scope: 'company',
    dimensions: ['new_strategy', 'new_needs'],
    decayDays: 210,
    buyerFunctions: ['commercial', 'quality_and_compliance', 'regulatory_affairs'],
    intentMechanisms: ['strategy_shift', 'complexity_increased'],
    notes: 'Important late-stage / approved product signal.',
  },
  {
    signalKey: 'publication',
    scope: 'company',
    dimensions: ['new_strategy'],
    decayDays: 45,
    buyerFunctions: ['research_and_development', 'medical_affairs'],
    intentMechanisms: ['strategy_shift'],
    notes: 'Mostly narrative/context.',
  },
  {
    signalKey: 'new_paper_published',
    scope: 'contact',
    dimensions: ['new_strategy'],
    decayDays: 45,
    buyerFunctions: [],
    intentMechanisms: ['strategy_shift'],
    notes: 'Buyer function should be derived from the contact classification.',
  },
  {
    signalKey: 'principal_investigator_new_trial',
    scope: 'contact',
    dimensions: ['new_strategy', 'new_needs'],
    decayDays: 60,
    buyerFunctions: ['clinical_operations', 'research_and_development', 'medical_affairs'],
    intentMechanisms: ['program_advance', 'complexity_increased'],
    notes: 'Matched from ClinicalTrials.gov overallOfficials field when PI name matches a contact.',
  },
  {
    signalKey: 'patent_filed_or_granted',
    scope: 'company',
    dimensions: ['new_strategy'],
    decayDays: 120,
    buyerFunctions: ['research_and_development', 'strategy_and_corporate_development'],
    intentMechanisms: ['strategy_shift'],
    notes: 'Not enough alone to indicate buying timing.',
  },
  {
    signalKey: 'patent_application_published',
    scope: 'company',
    dimensions: ['new_strategy'],
    decayDays: 180,
    buyerFunctions: ['research_and_development', 'strategy_and_corporate_development'],
    intentMechanisms: ['strategy_shift', 'program_advance'],
    notes: 'New published applications can indicate active pipeline and IP investment.',
  },
  {
    signalKey: 'patent_granted',
    scope: 'company',
    dimensions: ['new_strategy', 'new_needs'],
    decayDays: 240,
    buyerFunctions: ['research_and_development', 'commercial', 'strategy_and_corporate_development'],
    intentMechanisms: ['strategy_shift', 'program_advance'],
    notes: 'Granted patents can support commercialization and program execution readiness.',
  },
  {
    signalKey: 'new_therapeutic_area_patent',
    scope: 'company',
    dimensions: ['new_strategy', 'new_needs'],
    decayDays: 240,
    buyerFunctions: ['research_and_development', 'business_development', 'strategy_and_corporate_development'],
    intentMechanisms: ['strategy_shift', 'complexity_increased'],
    notes: 'Patent activity in a new therapeutic area implies expansion and net-new demand creation.',
  },
  {
    signalKey: 'assignee_portfolio_acceleration',
    scope: 'company',
    dimensions: ['new_strategy'],
    decayDays: 150,
    buyerFunctions: ['research_and_development', 'strategy_and_corporate_development'],
    intentMechanisms: ['program_advance', 'strategy_shift'],
    notes: 'Higher filing/grant velocity often indicates rising program tempo.',
  },
  {
    signalKey: 'trial_failure_or_halt',
    scope: 'company',
    dimensions: ['caution'],
    decayDays: 240,
    buyerFunctions: ['clinical_operations', 'executive_leadership'],
    intentMechanisms: ['suppression'],
    notes: 'Particularly important in biotech.',
  },
  {
    signalKey: 'program_discontinuation',
    scope: 'company',
    dimensions: ['caution'],
    decayDays: 240,
    buyerFunctions: ['research_and_development', 'clinical_operations'],
    intentMechanisms: ['suppression'],
    notes: 'Suppresses relevance for associated programs.',
  },
  {
    signalKey: 'restructuring',
    scope: 'company',
    dimensions: ['caution'],
    decayDays: 180,
    buyerFunctions: ['executive_leadership', 'procurement'],
    intentMechanisms: ['suppression'],
    notes: 'Can coexist with strategy signals; caution should still apply.',
  },
  {
    signalKey: 'acquisition_distraction',
    scope: 'company',
    dimensions: ['caution'],
    decayDays: 150,
    buyerFunctions: ['executive_leadership', 'strategy_and_corporate_development'],
    intentMechanisms: ['suppression'],
    notes: 'Used when integration timing likely slows buying.',
  },
  {
    signalKey: 'leadership_churn',
    scope: 'company',
    dimensions: ['caution', 'new_people'],
    decayDays: 120,
    buyerFunctions: ['executive_leadership', 'business_development', 'clinical_operations', 'manufacturing_and_cmc'],
    intentMechanisms: ['suppression', 'leadership_change'],
    notes: 'Can create change, but often noisy.',
  },
  {
    signalKey: 'prior_customer_relationship',
    scope: 'contact',
    dimensions: ['new_budget', 'new_people'],
    decayDays: 365,
    buyerFunctions: [],
    intentMechanisms: ['budget_created', 'leadership_change'],
    notes: 'Contact moved from a closed-won account. Strong warm-start signal at the new company.',
  },
  {
    signalKey: 'prior_active_deal_relationship',
    scope: 'contact',
    dimensions: ['new_budget', 'new_people'],
    decayDays: 180,
    buyerFunctions: [],
    intentMechanisms: ['budget_created', 'leadership_change'],
    notes: 'Contact moved from a company with an active deal in the pipeline.',
  },
  {
    signalKey: 'prior_pipeline_relationship',
    scope: 'contact',
    dimensions: ['new_people'],
    decayDays: 90,
    buyerFunctions: [],
    intentMechanisms: ['leadership_change'],
    notes: 'Contact previously in the pipeline at their prior company (closed-lost or context-only).',
  },
  {
    signalKey: 'terminated_deal',
    scope: 'company',
    dimensions: ['new_strategy', 'new_needs'],
    decayDays: 180,
    buyerFunctions: ['strategy_and_corporate_development', 'business_development', 'executive_leadership'],
    intentMechanisms: ['strategy_shift', 'complexity_increased'],
    notes:
      'A terminated material agreement signals strategic change and a potential gap to fill. ' +
      'Service agreement termination (CRO, CMO) → new_needs (may seek alternative vendors). ' +
      'Partnership/license termination → new_strategy (asset now unencumbered, new direction). ' +
      'Termination reason and counterparty type stored in metadata for ICP relevance filtering.',
  },
  {
    signalKey: 'lapsed_customer',
    scope: 'company',
    dimensions: ['caution'],
    decayDays: 365,
    buyerFunctions: ['commercial'],
    intentMechanisms: ['suppression'],
    notes: 'First-party relationship warning.',
  },
  {
    signalKey: 'key_contact_departed',
    scope: 'company',
    dimensions: ['new_people', 'new_strategy'],
    decayDays: 120,
    buyerFunctions: [],
    intentMechanisms: ['leadership_change', 'strategy_shift'],
    notes: 'A known contact at this account moved to a new company. Creates an opportunity to re-establish with their replacement.',
  },
] as const;

export const READINESS_SIGNAL_CATALOG: readonly SignalCatalogEntry[] =
  RAW_READINESS_SIGNAL_CATALOG.map(withImpact);

export const READINESS_SIGNAL_CATALOG_BY_KEY: Readonly<Record<SignalKey, SignalCatalogEntry>> =
  READINESS_SIGNAL_CATALOG.reduce((acc, entry) => {
    acc[entry.signalKey] = entry;
    return acc;
  }, {} as Record<SignalKey, SignalCatalogEntry>);

export function getReadinessSignal(signalKey: SignalKey): SignalCatalogEntry {
  return READINESS_SIGNAL_CATALOG_BY_KEY[signalKey];
}

export function getSignalBaseImpactScore(signalKey: SignalKey): number {
  return READINESS_SIGNAL_CATALOG_BY_KEY[signalKey]?.baseImpactScore ?? 0;
}

export function getSignalsForDimension(dimension: SignalCatalogEntry['dimensions'][number]): SignalCatalogEntry[] {
  return READINESS_SIGNAL_CATALOG.filter((entry) => entry.dimensions.includes(dimension));
}
